version: '3.1'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring
    ports:
      - "5432:5432"
    volumes:
      - ./sandbox/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d spring" ]
      interval: 10s
      timeout: 5s
      retries: 10